version: "3.9"

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - CORS_ORIGINS=http://localhost:3000,*
    networks:
      - app-network

  logger:
    build:
      context: ./Logger
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    environment:
      - CORS_ORIGINS=http://localhost:3000,*
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - API_URL=http://backend:8000
    networks:
      - app-network

  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:8000
      - NEXT_PUBLIC_LOGGER_URL=http://localhost:8001
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  # Add any persistent storage if needed
  data:
    driver: local
