[workspace]
channels = ["conda-forge"]
name = "Backend"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
backend = "uvicorn main:app --host 0.0.0.0 --port 8000"

[dependencies]
fastapi = ">=0.116.1,<0.117"
uvicorn = ">=0.35.0,<0.36"
pydantic = ">=2.11.7,<3"
transformers = ">=4.55.0,<5"

[pypi-dependencies]
torch = ">=2.8.0, <3"
